# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'COSTestDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for COSTestDemo
  pod 'QCloudCOSV4', :path => "../"
  target 'COSTestDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COSTestDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
